apiVersion: v2
name: thumbor
description: Thumbor(https://github.com/thumbor/thumbor) Helm chart.
type: application
version: 0.1.0
appVersion: "7.1.1"
dependencies:
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami
